name: PR Test

on:
  pull_request:
    branches: [ master ] # master branch에 PR을 보낼 때 실행

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: test
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      # Gradle Cache 추가
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-   

      # Gradle wrapper 파일 실행 권한주기
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run test
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          DB_NAME: member
          DB_USER: root
          DB_PASSWORD: test
        run: |
          sudo service mysql restart
          echo $DB_HOST 
          echo $DB_PORT
          mysql --host $DB_HOST --port $DB_PORT -uroot -ptest -e 'CREATE SCHEMA `Member` CHARACTER SET utf8 COLLATE utf8_general_ci';  

      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
